### ISSUE TITLE
There is no local cache for CRL

### ISSUE THREAD

**Issue by iaomw** [readium/r2-testapp-swift#123]
The description is in the comment below.

**Comment by llemeurfr** [comment]
The app should try to load the CRL each (decide a period, maybe a week) at most, at the time the app is launched. 
The cached value must be used until a new CRL can be loaded.
The user may have kept his device offline since the installation of the app. Therefore the app may never be able to fetch the CRL. In such a case, the user should still be able to access publications importer in the app.

**Comment by aferditamuriqi** [comment]
closed by https://github.com/readium/r2-testapp-swift/pull/126/
