### ISSUE TITLE
LCP: missing warning if importing a license but 404 content link

### ISSUE THREAD

**Issue by llemeurfr** [readium/r2-testapp-swift#235]
Let's take a license from a local + inactive LCP server, import it in the test app. The import fails because the content is not reachable through the frontend server. But the user sees no message; it should. The error message can be "Import failed because remote content is unreachable".

**Comment by mmenu-mantano** [comment]
Actually there's an error but only after a timeout of ~60 seconds. This seems to only occur when using a local address: I tried using a random domain name instead of 192.168... in the license, and it failed immediately.

However, the reported error is "This license is expired" which is wrong, I will fix this.
