### ISSUE TITLE
LCP: error msg when after starting reading a protected ebook

### ISSUE THREAD

**Issue by llemeurfr** [readium/r2-testapp-swift#236]
After successfully importing a license + associated content, opening the book using the passphrase, 
the device is left idle. After some time, when taking the device back, a message appeared with no reason: "The operation couldn't be completed. Software caused connection abort". 
After pressing OK, reading can continue.

**Comment by mmenu-mantano** [comment]
I didn't manage to reproduce this bug, using the simulator and a real device. Does it happen every time? I let the screen switch off on its own, and I also tried closing it manually right after opening the book.

From what I found online, this is caused by a network request that is interrupted when the app goes in background. I don't think that this is directly related to LCP because there're no more requests made after the book is opened (unless you perform a Renew/Return). You can see that in the console, all the calls to NetworkService in LCP are logged. However, that could be a regular request made from the web view to the publication server to load some content. But it's weird that it happens if you leave the screen switch off on its own.

**Comment by llemeurfr** [comment]
I just had this issue with a *huge* audiobook, but it was during the download phase.

**Comment by llemeurfr** [comment]
closing as not reproduced.
