### ISSUE TITLE
LCP: issue with ToC

### ISSUE THREAD

**Issue by llemeurfr** [readium/r2-testapp-swift#264]
Licenses taken from front-prod.edrlab.org. 

On Moby-Dick, the ToC is empty.
On Waste Land the Toc is present but does not work.

**Comment by mmenu-mantano** [comment]
The empty toc on moby-dick is fixed by this PR https://github.com/readium/r2-streamer-swift/pull/105

For Wasteland, the `scrollToId` function in `utils.js` doesn't work (I tried using it directly in the web inspector). But it hasn't been touched for 2 years so it might be a problem specifically with this book.

**Comment by mmenu-mantano** [comment]
I found a solution and documented it in an issue on r2-streamer. There's already too much PR in the waiting list and I want to avoid merging pain.
https://github.com/readium/r2-streamer-swift/issues/107
