### ISSUE TITLE
Can not continue reading epub when devices go to background mode and come back again

### ISSUE THREAD

**Issue by judares** [readium/r2-testapp-swift#288]
Procedure:
1. Open any test file
2. Go to background mode
3. Open app again and continue reading
4. Swipe to next chapter 
5. Occur black screen with cbz format and the loading indicator with epub format (see above)

Test Environment:
iPhone SE - iOS 11.4.1
iPhone X - iOS 12.2
R2 Test App 2.0.1 Build 4

I think there is a problem with GCDWebservers when go to background mode.
Hope for your help, thank you!
@HadrienGardeur @llemeurfr 

![IMG_2255](https://user-images.githubusercontent.com/24771109/60642862-7691f400-9e5b-11e9-959a-889394770948.PNG)
![IMG_2256](https://user-images.githubusercontent.com/24771109/60642865-772a8a80-9e5b-11e9-8da2-1d00926d21d7.PNG)

**Comment by mmenu-mantano** [comment]
I did a few tests, I think it comes from the fact that [the port is now random](https://github.com/readium/r2-testapp-swift/issues/200). Every time we get out of background mode the server gets a new port:

```
[INFO] GCDWebServer stopped
[INFO] GCDWebServer started on port 55005 and reachable at http://localhost:55005/
[INFO] GCDWebServer stopped
[INFO] GCDWebServer started on port 55012 and reachable at http://localhost:55012/
```

Here's a few possible solutions:

- Setting [`GCDWebServerOption_AutomaticallySuspendInBackground`](https://github.com/swisspol/GCDWebServer#gcdwebserver--background-mode-for-ios-apps) but this might cause further issues (for example Apple refusing the app because it stays active in the background for no reason).
- Fixing the port once it is randomly chosen, if it's possible.
- Updating all the served Publications' `self` links with the new port. There might be additional side effects if some URI is cached somewhere.

**Comment by judares** [comment]
I changed to use fixed port in r2-streamer-swift. It doesn't occur any more. Thank you so much!
`    internal func startWebServer() -> Bool {
        // with port 0, a random port is used each time.
//        let port = 0
        #if DEBUG
        let port = 8080
        #else
        let port = 1337
        #endif
        do {
            // TODO: Check if we can use unix socket instead of tcp.
            //       Check if it's supported by WKWebView first.
            try webServer.start(options: [GCDWebServerOption_Port: port,
                                          GCDWebServerOption_BindToLocalhost: true])
        } catch {
            log(.error, "Failed to start the HTTP server: \(error)")
            return false
        }
        return true
    }`

**Comment by mmenu-mantano** [comment]
Using a fixed port causes other issues though (as described here https://github.com/readium/r2-testapp-swift/issues/200). We're trying to come up with a proper solution.

**Comment by mmenu-mantano** [comment]
This should fix the issue: https://github.com/readium/r2-streamer-swift/pull/125

**Comment by HadrienGardeur** [comment]
Keep in mind that iPadOS can run the same apps many times in parallel, so we'll need to come up with a solution for that as well.

**Comment by JayPanoz** [comment]
Ah friendly reminder there is [an origin doc in architecture](https://github.com/readium/architecture/blob/master/server/origin.md) and documenting a proper solution as best practice/solution will be greatly appreciated – otherwise you can drop a technical summary with related links in my mailbox/Slack DM and I’ll update the doc.
