### ISSUE TITLE
book opening to be "debounced"

### ISSUE THREAD

**Issue by llemeurfr** [readium/r2-testapp-swift#29]
If I tap quickly several times on a cover, the book seems to "stack", be opened several times, one book appearing over the other. If I use the back action, the book isn't closed, but I "come back" to the "book below".

**Comment by iaomw** [comment]
OK, looks like easy task. We can simply disable user interaction then enable it after the book loading is done or failed.  I cannot reproduce it after that fix.

As the previous discuss, this issue is especially for LCP books. Because it's very slow to open LCP book. I also noticed there is no indicator or animation when the book is been downloading or loading. It feels totally strange. At least we should told the using what's going on.

My project setup got too much conflict with master. After this, we should add some visual indicator and animation at least for downloading and opening book. It could be modal style or just some small visual indicator.
