### ISSUE TITLE
LCP: block sharing more than the number of allowed characters

### ISSUE THREAD

**Issue by llemeurfr** [readium/r2-testapp-swift#295]
Copy/paste and sharing must be submitted to the same rule. One should not be able to share more characters than allowed.

**Comment by mickael-menu** [comment]
There's no way to customize the default Share action in the selection menu (private API), so to fix this I had to remake the Share action from scratch. Which means that now the selection contents is retrieved using JavaScript instead of relying on the default `UIPasteboard` behavior.

This works fine but there's a side effect: we can't copy non-text contents anymore (eg. images). If this is undesired, we could override the Copy/Share only for LCP publications and let the native behavior run for other publications.

There is still an issue with PDF on iOS 13. Somehow, the previous way of overriding a context menu item doesn't work anymore, and I couldn't find a way to prevent the native Share and Look-Up actions to be displayed yet. It might be caused by a change in the internal views hierarchy of `PDFView`. There's no issue with EPUB on iOS 13.

(I just noticed that the tap doesn't work either on iOS 13, there's definitely some issues with the new `PDFKit` view hierarchy https://github.com/readium/r2-navigator-swift/issues/82)

<img width="639" alt="Screenshot 2019-10-24 at 16 01 14" src="https://user-images.githubusercontent.com/6561221/67494550-a28aec80-f679-11e9-964b-65214f572577.png">
