### ISSUE TITLE
Some of the content in Table of Contents is not rendered

### ISSUE THREAD

**Issue by rkwright** [readium/r2-testapp-swift#7]
If one opens the [EPUB Test Suite 150](http://epubtest.org/epubs/epub30-test-0150-20160116.epub) (Navigation)  and then open the TOC, most of the elements of the TOC are rendered, but not all.  In particular, the *sub-category* CSS class elements of the <nav> are not rendered.  The element is apparently present because the link **works**  (if you click on the empty space you are taken to the right spot in the document) but nothing is rendered.

*Procedure:*
1. Open the test document (see above)
2. Open the TOC
3. Observe that none of the sub-categories (e.g. landmarks, test-links, etc.) are rendered.

*Test Environment:*
iPad 5, 16 GB
iOS 11.0.3
R2 Test App 0.2 (2)

**Comment by HadrienGardeur** [comment]
This sounds like a rendering/presentation issue IMO.

It would be useful to include the full JSON manifest output in the app, this way you could double check what's in there as well.

**Comment by rkwright** [comment]
Agreed that it is a rendering/presentation issue.  The markup is:


    <h1 class="title">Table of Contents</h1>
			<ol>
				<li id="front"><a href="front.xhtml">Front page</a></li>
				<li id="nav"><a href="nav.xhtml">Table of Contents</a></li>
				<li class="subcategory"><a href="epubnav-002.xhtml#toc-nav"><code>toc nav</code></a>
					<ol>
						<li><a href="epubnav-002.xhtml#epubnav-010">Access</a></li>
						<li><a href="epubnav-002.xhtml#epubnav-020">Document-level linking</a></li>
						<li><a href="epubnav-002.xhtml#epubnav-030">Fragment-level linking</a></li>
					</ol>
				</li>

But there is no such class as "subcategory" in the CSS file.

**Comment by garconvacher** [comment]
Adding .subcategory in CSS file didn't change the rendering but remove the <code> tags did ;-)

**Comment by gbugniot** [comment]
To be sure it's a rendering problem, I'm checking if there is nothing wrong in the Swift native part, especially with the streamer.

**Comment by gbugniot** [comment]
So Table of Contents is a full native UI control, which means that there is no HTML/CSS rendering.

Looking at [NavigationDocumentParser.swift](https://github.com/readium/r2-streamer-swift/blob/master/Sources/parser/NavigationDocumentParser.swift#L143-L198), we can see that a `span` tag is handled but not a `code` tag.

It could be fixed, following the same pattern than the one used to handle `span`. I'm going to implement this on a `bugfix` branch, if there is no disagreement.

**Comment by gbugniot** [comment]
Yes, hardcoding tags to handle is not a reliable solution in the long run.

**Comment by llemeurfr** [comment]
Pls check the EPUB 3.1 spec. 
A priori act at the "li" level, strip any inner tag, display the resulting plain text.

**Comment by gbugniot** [comment]
After some research and experimentation I found an easy way to get rid of inner tags: [NSAttributedString API from Apple](https://developer.apple.com/documentation/foundation/nsattributedstring/1524613-init).

We basically pass the AEXML element (in our case the `<a>` tag), we set how the element should be handled  by the the function (here, it's XML/HTML), then it returns the string without tags. 

It works well with this kind of XML:
`<a href="epubnav-004.xhtml#page-list-nav"><code>page-list nav</code></a>`
Returned text is: `page-list nav`

In this case, it doesn't work:
`<a href="epubnav-005.xhtml#custom-nav">Custom <code>nav</code> elements</a>`
Returned text is: `nav`

But the problem is related to AEXML, because if I pass directly this raw XML string to NSAttributedString API, without using the AEXML parsed document I get the correct text value: `Custom nav elements`

**Comment by HadrienGardeur** [comment]
That's another good reason for getting rid of AEXML. I think this should be a high priority given the number of bugs that are specific to it.
